version: '2'

services:

  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: "notification-service-zookeeper"
    networks:
      - 'notification-service-network'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # See:
  # https://hub.docker.com/r/bitnami/kafka
  kafka:
    image: bitnami/kafka:2.5.0
    container_name: 'notification-service-kafka'
    networks:
      - 'notification-service-network'
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://10.5.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  web:
    build: .
    command: npm run start
    container_name: 'notification-service-web'
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    networks:
      - 'notification-service-network'
    ports:
      - "3000:3000"
    depends_on:
      - kafka

networks:
  notification-service-network:
    name: 'notification-service-network'
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
          ip_range: 10.5.0.0/24
          gateway: 10.5.0.1
          aux_addresses:
            kafka: 10.5.0.2
            zookeeper: 10.5.0.3